org: bonzaipj
service: bonzai

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-north-1 # Stockholm
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:GetItem
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:DeleteItem
      Resource:
        - arn:aws:dynamodb:eu-north-1:*:table/bonzai-table

build:
  esbuild:
    minify: true

package:
  individually: true

functions:
  getRooms:
    handler: functions/getRooms/index.handler
    events:
      - httpApi:
          path: /rooms
          method: get

  postRooms:
    handler: functions/postRooms/index.handler
    events:
      - httpApi:
          path: /rooms
          method: post

  getBookings:
    handler: functions/getBookings/index.handler
    events:
      - httpApi:
          path: /bookings
          method: get

  updateBooking:
    handler: functions/updateBooking/index.handler
    events:
      - httpApi:
          path: /bookings/{id}
          method: put

  cancelBooking:
    handler: functions/cancelBooking/index.handler
    events:
      - httpApi:
          path: /bookings/{id}
          method: delete

