org: bonzaipj
service: bonzai

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-north-1 # Stockholm
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:GetItem
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:DeleteItem
      Resource:
        - arn:aws:dynamodb:eu-north-1:*:table/bonzai-table

build:
  esbuild:
    minify: true

package:
  individually: true

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get

  createBooking:
    handler: handler.createBooking
    events:
      - httpApi:
          path: /bookings
          method: post

  getBooking:
    handler: handler.getBooking
    events:
      - httpApi:
          path: /bookings/{id}
          method: get

resources:
  Resources:
    BookingsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Bookings
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: bookingId
            AttributeType: S
        KeySchema:
          - AttributeName: bookingId
            KeyType: HASH
